/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphics.metier;

import classe.metier.Adresse;
import javax.swing.JOptionPane;
import taxi.DAO.AdresseDAO;

/**
 *
 * @author lionn
 */
public class CreaAdr extends javax.swing.JPanel {

    /**
     * Creates new form CreaAdr
     */
    AdresseDAO adresseDAO = null;

    public CreaAdr() {
        initComponents();
    }

    public void setAdresseDAO(AdresseDAO adresseDAO) {
        this.adresseDAO = adresseDAO;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        loca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rue = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Num = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1298, 619));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        jLabel1.setText("Code Postal :");
        add(jLabel1);
        jLabel1.setBounds(420, 178, 112, 18);
        add(cp);
        cp.setBounds(677, 178, 261, 26);

        jLabel2.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        jLabel2.setText("Localité :");
        add(jLabel2);
        jLabel2.setBounds(420, 232, 78, 18);

        loca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locaActionPerformed(evt);
            }
        });
        add(loca);
        loca.setBounds(677, 232, 261, 26);

        jLabel3.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        jLabel3.setText("Rue :");
        add(jLabel3);
        jLabel3.setBounds(420, 290, 45, 18);

        rue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rueActionPerformed(evt);
            }
        });
        add(rue);
        rue.setBounds(677, 290, 261, 26);

        jLabel4.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        jLabel4.setText("Numéro :");
        add(jLabel4);
        jLabel4.setBounds(420, 345, 81, 18);
        add(Num);
        Num.setBounds(677, 345, 261, 26);

        add.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        add.setText("Ajouter");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        add(add);
        add.setBounds(420, 406, 112, 40);

        jLabel5.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 24)); // NOI18N
        jLabel5.setText("Taxi Voitus");
        add(jLabel5);
        jLabel5.setBounds(563, 60, 179, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void locaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locaActionPerformed

    private void rueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rueActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        try {
            int code = Integer.parseInt(cp.getText());
            String loc = loca.getText();
            String r = rue.getText();
            String n = Num.getText();
            Adresse adr = new Adresse(0, code, loc, r, n);
            adresseDAO.create(adr);
            JOptionPane.showMessageDialog(this, "Adresse créé", "Succès", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERREUR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_addActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Num;
    private javax.swing.JButton add;
    private javax.swing.JTextField cp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField loca;
    private javax.swing.JTextField rue;
    // End of variables declaration//GEN-END:variables
}
