/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphics.metier;

import classe.metier.Adresse;
import classe.metier.Client;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import taxi.DAO.AdresseDAO;
import taxi.DAO.ClientDAO;

/**
 *
 * @author lionn
 */
public class CreaCli extends javax.swing.JPanel {

    /**
     * Creates new form CreaCli
     */
    ClientDAO clientDAO = null;
    AdresseDAO adresseDAO = null;
    DefaultComboBoxModel dlm = new DefaultComboBoxModel();
    List<Adresse> afl;

    public CreaCli() {
        initComponents();
        
    }

    /*public void inject_adr() {
        try {
            afl = adresseDAO.aff();
            System.out.println(afl);
            for (int i = 0; i < afl.size(); i++) {
                dlm.addElement(afl.get(i).toString());

            }
            adr.setModel(dlm);

        } catch (Exception e) {
            System.out.println("Exception" + e);
        }
    }*/
    public void inject_adr() {
        try {
            afl = adresseDAO.aff();

            if (adr != null) {
                adr.removeAllItems();

            }
            System.out.println(afl);
            for (int i = 0; i < afl.size(); i++) {
                dlm.addElement(afl.get(i).toString());

            }
            adr.setModel(dlm);

        } catch (Exception e) {
            System.out.println("Exception" + e);
        }
    }

    public void setAdresseDAO(AdresseDAO adresseDAO) {
        this.adresseDAO = adresseDAO;
    }

    public void setClientDAO(ClientDAO clientDAO) {
        this.clientDAO = clientDAO;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        adr = new javax.swing.JComboBox<>();
        tel = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1298, 619));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        jLabel1.setText("Nom :");
        add(jLabel1);
        jLabel1.setBounds(251, 183, 51, 18);

        jLabel2.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        jLabel2.setText("Prénom :");
        add(jLabel2);
        jLabel2.setBounds(250, 240, 80, 18);

        jLabel3.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        jLabel3.setText("Téléphone :");
        add(jLabel3);
        jLabel3.setBounds(251, 289, 99, 18);

        jLabel4.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 14)); // NOI18N
        jLabel4.setText("Adresse :");
        add(jLabel4);
        jLabel4.setBounds(251, 333, 83, 18);

        adr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        adr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adrActionPerformed(evt);
            }
        });
        add(adr);
        adr.setBounds(539, 328, 414, 26);
        add(tel);
        tel.setBounds(539, 284, 414, 26);
        add(prenom);
        prenom.setBounds(539, 230, 414, 26);
        add(nom);
        nom.setBounds(539, 175, 414, 26);

        jButton1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(251, 447, 93, 23);

        jLabel5.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 24)); // NOI18N
        jLabel5.setText("Taxi Voitus");
        add(jLabel5);
        jLabel5.setBounds(571, 68, 179, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void adrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adrActionPerformed


    }//GEN-LAST:event_adrActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String n = nom.getText();
            String pr = prenom.getText();
            String t = tel.getText();
            int pos = adr.getSelectedIndex();
            Adresse adr = afl.get(pos);
            System.out.println(adr.getIdadr());
            Client cl = new Client(0, n, pr, t, adr.getIdadr());
            clientDAO.create(cl);
            JOptionPane.showMessageDialog(this, "Client  créé", "Succès", JOptionPane.INFORMATION_MESSAGE);
            inject_adr();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERREUR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> adr;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField prenom;
    private javax.swing.JTextField tel;
    // End of variables declaration//GEN-END:variables
}
