/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphics.metier;

import classe.metier.Adresse;
import classe.metier.Client;
import classe.metier.Location;
import classe.metier.Voiture;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import taxi.DAO.AdresseDAO;
import taxi.DAO.ClientDAO;
import taxi.DAO.LocationDAO;
import taxi.DAO.TaxiDAO;

/**
 *
 * @author lionn
 */
public class Trouve_loc extends javax.swing.JPanel {

    /**
     * Creates new form Trouve_loc
     */
    DefaultComboBoxModel dlmtx = new DefaultComboBoxModel();
    LocationDAO locationDAO = null;
    TaxiDAO taxiDAO = null;
    ClientDAO clientDAO = null;
    AdresseDAO adresseDAO = null;
    DefaultTableModel dft1 = new DefaultTableModel();
    List<Voiture> vtl;

    public Trouve_loc() {

        initComponents();
        dft1.addColumn("idloc");
        dft1.addColumn("DateLoc");
        dft1.addColumn("Kmtotal");
        dft1.addColumn("acompte");
        dft1.addColumn("total");
        dft1.addColumn("taxi");
        dft1.addColumn("client");
        dft1.addColumn("adresse de départ");
        dft1.addColumn("adresse de fin");
        locatab.setModel(dft1);
    }

    public void setLocationDAO(LocationDAO locationDAO) {
        this.locationDAO = locationDAO;
    }

    public void setTaxiDAO(TaxiDAO taxiDAO) {
        this.taxiDAO = taxiDAO;
    }

    public void setAdresseDAO(AdresseDAO adresseDAO) {
        this.adresseDAO = adresseDAO;
    }

    public void setClientDAO(ClientDAO clientDAO) {
        this.clientDAO = clientDAO;
    }

    public void inject_taxi() {
        try {
            vtl = taxiDAO.aff();
            if (taxi != null) {
                taxi.removeAllItems();
            }

            for (int i = 0; i < vtl.size(); i++) {
                dlmtx.addElement(vtl.get(i).toString());

            }
            taxi.setModel(dlmtx);

        } catch (SQLException e) {
            System.out.println("Exception" + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        taxi = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        locatab = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 14)); // NOI18N
        jLabel1.setText("Taxi :");
        add(jLabel1);
        jLabel1.setBounds(209, 188, 35, 18);

        taxi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(taxi);
        taxi.setBounds(300, 180, 506, 26);

        jButton1.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 14)); // NOI18N
        jButton1.setText("Rechercher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(922, 184, 125, 27);

        locatab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(locatab);

        add(jScrollPane1);
        jScrollPane1.setBounds(67, 222, 1082, 322);

        jLabel2.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 24)); // NOI18N
        jLabel2.setText("Taxi Voitus");
        add(jLabel2);
        jLabel2.setBounds(520, 94, 184, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            int id = taxi.getSelectedIndex();
            Voiture t = vtl.get(id);
            System.out.println(t.getIdtaxi());
            List<Location> locl = locationDAO.affloctx(t.getIdtaxi());
            System.out.println(locl);
            int nr = dft1.getRowCount();
            for (int i = nr - 1; i >= 0; i--) {
                dft1.removeRow(i);
            }

            for (Location l : locl) {
                Vector v = new Vector();
                v.add(l.getIdloc());
                System.out.println(v);
                v.add(l.getDateloc());
                System.out.println(v);
                v.add(l.getKmtotal());
                System.out.println(v);
                v.add(l.getAcompte());
                System.out.println(v);
                v.add(l.getTotal());
                System.out.println(v);
                t = taxiDAO.read(l.getFktaxi());
                v.add(t.getImma());
                System.out.println(v);
                Client c = clientDAO.read(l.getFkclient());
                v.add(c.getNom());
                Adresse ad = adresseDAO.read(l.getIdadr_deb());
                Adresse af = adresseDAO.read(l.getIdadr_fin());
                v.add(ad.getNum() + ",Rue " + ad.getRue() + " " + ad.getLocalite());
                v.add(af.getNum() + ",Rue" + af.getRue() + " " + af.getLocalite());
                System.out.println(v);
                dft1.addRow(v);
            }
        } catch (SQLException e) {
            System.out.println("Exception " + e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable locatab;
    private javax.swing.JComboBox<String> taxi;
    // End of variables declaration//GEN-END:variables
}
